### ISSUE TITLE
Is there a callback or something to remove validation?

### ISSUE THREAD

**Issue by syberknight** [sepiariver/recaptchav2#10]
i've been hunting, pecking, & trying SO many suggestions and nothing's working.

i found this cool idea @ http://www.ivanthevariable.com/combining-googles-recaptcha-and-jquery-validate

and since i'm using Jquery Validate for the rest of my form, i gave it a try. 

it works great when trying to submit the form without hitting the captcha. but then when you do the captcha & the captcha gets the green checkmark, the validation doesn't go away.

in looking at the source before/after, it would seem nothing on my end gets any change back from google's end. i read in the API about the callback & stuff, but of course it's over my head.
(re: https://developers.google.com/recaptcha/docs/display -and- https://developers.google.com/recaptcha/docs/verify)

any insight would be appreciated.
.peace.:.jason.

**Comment by sepiariver** [comment]
Hmm... I'll have to look into this more thoroughly but I suspect you need the site's secret key to make the validation request, so it's meant to be server-side only. Unless you want to hand out your secret key in your front end code but I don't think that's a good idea...

**Comment by syberknight** [comment]
cool, thanks.
and no, i don't want to hand out my secret key (lol).

**Comment by multireadsts** [comment]
Same issue but using no jquery validate.

**Comment by sepiariver** [comment]
@multireadsts sorry I thought this issue was closed lol.

you mean you want to do client-side validation without jQuery? If so, jQuery really isn't the issue here, it's the exposing of your API key on the front-end. 

For most use cases people will want to control and keep the API key secret on the server side...

**Comment by multireadsts** [comment]
Thanks for your response. It’s no issue anymore.
- Stefan

Von meinem iPhone gesendet
