### ISSUE TITLE
Error occurs on submit (2.0.2-rc1)

### ISSUE THREAD

**Issue by Gareth-Bevan** [sepiariver/recaptchav2#11]
Hi, Thanks for creating this, it's a great feature.

I had an issue getting the latest update(2.0.2-rc1) to work, It displayed correctly, but I kept getting a 500 error when I submitted the form. The php error log stated "PHP Parse error: syntax error, unexpected T_STRING in C:\inetpub\wwwroot......\core\cache\includes\elements\modsnippet\13.include.cache.php on line 51" (this is the cached copy of the 'recaptchav2' snippet). In the end I rolled back to version "recaptchav2-1.0.0-rc1" which works correctly. Do you know why this would happen? Does it require a minimum version of php?

++php error+++
PHP Parse error:  syntax error, unexpected T_STRING in C:\inetpub\wwwroot............\core\cache\includes\elements\modsnippet\13.include.cache.php on line 51

++13.include.cache.php (cached file)++
[13.include.cache.txt](https://github.com/sepiariver/recaptchav2/files/174343/13.include.cache.txt)

**Comment by sepiariver** [comment]
Ok thanks for posting this @Gareth-Bevan 
What version of PHP are you running please?

**Comment by Gareth-Bevan** [comment]
5.2.14

**Comment by sepiariver** [comment]
Ok, that's the issue then. You had it right when you posted the comment. PHP namespaces are only supported in 5.3+

In general, MODX only supports 5.3+ now...
