### ISSUE TITLE
Error message lang

### ISSUE THREAD

**Issue by lawebfabric** [sepiariver/recaptchav2#12]
Hi,
Is there a way to change the error message language ?
Thanks in advance.

**Comment by bYemma** [comment]
A little bit late, but here is the answer: Add a new option in the system settings with name _recaptcha_error_message_ and the content is the error message.

For the tech error the key is _technical_error_message_.

You find that in recaptchav2-Snippet:
`$tech_err_msg = $modx->getOption('technical_error_message', $properties, 'Sorry, there was an error submitting your form. Please use one of the contacts on this page instead.');
$recaptcha_err_msg = $modx->getOption('recaptcha_error_message', $properties, 'Please select the checkbox in the ReCaptcha image.');`

**Comment by lawebfabric** [comment]
Thanks but I found it it by myself.
