### ISSUE TITLE
Not displaying with Register? 

### ISSUE THREAD

**Issue by getandyjones** [sepiariver/recaptchav2#13]
HI.
I am trying to use this on a register form.
I was using recaptcha V1 - and it's fine:
`
[[!Register?
    &submitVar=`registerbtn`
    &activationResourceId=`114`
    &activationEmailTpl=`lgnActivateEmailTpl`
    &activationEmailSubject=`Thanks for Registering with the LTDA!`
    &submittedResourceId=`113`
    &validate=`nospam:blank`
    &usergroups=`Members`
    &preHooks=`recaptcha`
]]
`
In the form I have this:
`       
 [[!+recaptcha_html]]
[[!+error.recaptcha]]
`

I have installed recaptchav2 and have swapped the snippet to:
`
[[!Register?
    &submitVar=`registerbtn`
    &activationResourceId=`114`
    &activationEmailTpl=`lgnActivateEmailTpl`
    &activationEmailSubject=`Thanks for Registering with the LTDA!`
    &submittedResourceId=`113`
    &validate=`nospam:blank`
    &usergroups=`Members`
    &preHooks=`recaptchav2`
]]
`

And am calling this in my form:
`
[[!recaptchav2_render]]
[[!+fi.error.recaptchav2_error]]
`
But it shows nothing. The keys etc are all there, as V1 was working.
Any ideas?

Thanks
Andy

**Comment by sepiariver** [comment]
@getandyjones  so sorry for the terrible response time on this. I hope you found the solution already but in case you didn't, I suspect the API keys need to be copied over to the v2 system settings. RecaptchaV2 is a separate package from Login and has it's own system settings.
