### ISSUE TITLE
Multiple reCaptcha on same page

### ISSUE THREAD

**Issue by lawebfabric** [sepiariver/recaptchav2#16]
Hi, is it possible to have multiple reCaptcha on the same page ?
I have two form on the page, one show the reCaptcha but not the other.

Thanks in advance.

**Comment by sepiariver** [comment]
This PR: https://github.com/sepiariver/recaptchav2/pull/14 addresses the issue but it may be too opinionated to be merged (see comment in the PR). 

You can, however, use the code there to implement multiple recaptcha's on the same page, if you wish.
