### ISSUE TITLE
recaptcha not validating

### ISSUE THREAD

**Issue by mtalvenheimo** [sepiariver/recaptchav2#17]
Hi,
For some reason recaptcha is not validating? (Formit hook). After submit I get formit error "Please select the checkbox in the ReCaptcha image."
I've setup Google APIKeys, system settings etc. All is done as in instructions. 
https://modx.com/extras/package/recaptchav2

Any idea what might be causing this?

**Comment by digitalbart** [comment]
I am getting a somewhat similar error when I check the box and submit it say invalid, even after the checkbox has turned to green. I am on modx 2.5.4-pl with formit 2.2.11-pl and reaptchav2 2.0.2-rc1

**Comment by matdave** [comment]
I am getting this issue too.  I was debugging all aspects of a custom form only to realize it was recaptcha failing.

**Comment by FlipFlop1974** [comment]
Same issue here. fi.error.recaptchav2_error holds the correct error message but FormIt ignores that and proceeds processing the form. Help would be highly appreciated. 

EDIT: Had managed it by my self right now. I had the problem, that my order in the hook call was wrong. For example: 
WRONG: &hooks=`email,FormItSaveForm,redirect,recaptchav2`

RIGHT: &hooks=`recaptchav2,email,FormItSaveForm,redirect`

This behavior belongs to FormIt and not to reCaptchav2 - FormIt parses the hooks as they come in given order and if recaptchav2 is the last, all hooks before will be processed. So in my WRONG example I got email, the form was saved and the page was redirected, even recaptchav2 has failed.
