### ISSUE TITLE
usage with quipRely

### ISSUE THREAD

**Issue by dubbsdubblin** [sepiariver/recaptchav2#22]
Hi - can this work with quipReply in MODx? I have it kind of working, recaptchaV2 renders - but, the validation fails - even when i tick the checkbox in the recaptchav2 - I am trying to validate the recaptchav2 using a  &preHooks=`recaptchav2` parameter on the quipReply code... Any ideas how to make it work with quip?

**Comment by sepiariver** [comment]
Have you tried this?

https://github.com/sepiariver/recaptchav2/issues/2
