### ISSUE TITLE
Please select the checkbox in the ReCaptcha image

### ISSUE THREAD

**Issue by 1ax** [sepiariver/recaptchav2#24]
an error occurs after you submit the form "Please select the checkbox in the ReCaptcha image"

**Comment by SirZockholm** [comment]
The same thing happens to me right now.
Did you find something? I'm almost certain I installed it correctly.

**Comment by sepiariver** [comment]
That error message means that something went wrong with the verification flow. Most often it's that the ReCaptcha response was not posted to the form handler correctly. Please check the post variables, and re-open this issue with some more information about the problem, if it persists. Thanks.
