### ISSUE TITLE
language not detected

### ISSUE THREAD

**Issue by elz64** [sepiariver/recaptchav2#28]
Hi,

reCaptcha v2 with Formit and Modx 2.6.3
No error in the log from it but not language detection.
Using 2 contexts (web = FR, EN = english) the text 'I'm not a robot' is always in the default language  (French') ' Je ne suis pas un robot'.
When I'm on the **english** contact form,
the rendered html code in the Google iFrame shows lang='fr' 
`html  dir="ltr" lang="fr"`

The [[++CultureKey] at this moment is however correct and set to 'en' ...?

**Comment by elz64** [comment]
I saw that Google captcha v2 DOS NOT use lang parameter but hl instead...
Where can I hack this if you can't ?
Thank you
<script type="text/javascript">
var recaptcha1;
var myCallBack = function() {
    //Render the recaptcha1 on the element with ID "recaptcha1"
    recaptcha1 = grecaptcha.render('recaptcha1', {
        'sitekey': '6LdJLws_your site key',
        'hl' : 'fr'
    });
};
</script>

**Comment by sepiariver** [comment]
Hi @elz64 hacking isn’t necessary you can just change it in the template Chunk used by the Snippet when you call it. `recaptchav2_html`
