### ISSUE TITLE
Fatel Error when used with Register snippet

### ISSUE THREAD

**Issue by bennyb** [sepiariver/recaptchav2#3]
Getting the following error when used with the login's Register snippet.

[10-Jul-2015 11:27:50 Europe/Amsterdam] PHP Fatal error:  Cannot redeclare class ReCaptchaResponse in /paas/XXXX/www/core/components/recaptchav2/model/recaptchav2/recaptchav2.class.php on line 39

I've tried this on a two servers one of which is MODX Cloud and i'm getting the error on both.

Initial Server details:
Login v1.9.0-pl
MODX 2.3.3
php - 5.4.36

MODX Cloud details
Login v1.9.0-pl
MODX 2.3.5
php -  5.4.42

**Comment by sepiariver** [comment]
Oh sorry initially I thought you said you were using the Login snippet, which I've tried, but I haven't tried with Register. 

I'll do that this weekend and see if I can get it to work or at least find out why :)

**Comment by bennyb** [comment]
That would be great, thanks

**Comment by sepiariver** [comment]
So I was mistaken — I'd never actually used it with the Login package. Only FormIt.

That said I figured out what the issue is and have a patch release coming.

**Comment by sepiariver** [comment]
Fixed here: https://github.com/sepiariver/recaptchav2/commit/8293bff6794f7319295a9a8e41b53e52910138d4

Pushing new version to Extras repo.

**Comment by bennyb** [comment]
Thanks for this working perfectly via modx PM, but looks like the package file on here is still 0.9.2.
