### ISSUE TITLE
score-threshold-not-met

### ISSUE THREAD

**Issue by sfleif** [sepiariver/recaptchav2#43]
Customers of a website can't use the contact form because of an "score-threshold-not-met" error. Is there anything we can change?

**Comment by sepiariver** [comment]
You can change the score threshold in the snippet properties :)

**Comment by Jako** [comment]
Could you document such hidden options?

**Comment by sepiariver** [comment]
Sorry about that it was a new feature in v3 and I forgot to mention it. Will make better docs for all my Extras in the new .org site :)

**Comment by sepiariver** [comment]
For clarity here:

```
&recaptchav3.threshold=`0.25`
```

In your FormIt call should work to lower the threshold for verification score, by half (default is .5)
