### ISSUE TITLE
error time-out V3

### ISSUE THREAD

**Issue by funkyduke** [sepiariver/recaptchav2#50]
Many times when using the plugin the user gets the following error message: 

timeout-or-duplicate hostname-mismatch
action-mismatch score-threshold-not-met

Most of the time it's when the user is a gmail or hotmail.

I use recaptcha v3

**Comment by sepiariver** [comment]
Those are all error responses from the Recaptcha API. This is actually the best reference for it: https://github.com/google/recaptcha/blob/master/src/ReCaptcha/ReCaptcha.php (although it’s not great documentation).

Some notes:

- timeout-or-duplicate - google this one for ideas, could be a lot of different things 
- hostname-mismatch - hostname must match that set in google https://security.stackexchange.com/questions/149324/why-bother-validating-the-hostname-for-a-google-recaptcha-response
- action-mismatch - ensure the action key is properly set
- score-threshold-not-met - users score was lower than default required. You can change this with Snippet properties
