### ISSUE TITLE
Support for multiple captchas

### ISSUE THREAD

**Issue by 5koder** [sepiariver/recaptchav2#8]
Would it be possible to have support for multiple recaptchas on one page? When I display the snippet on two separate Fomiit forms on the same page:

**[[!recaptchav2_render]]**
**[[!+fi.error.recaptchav2_error]]**

Only the very first captcha loads, The second one shows a blank space with this HTML:

`<div class="g-recaptcha" data-sitekey="6LdMbBQTAAAAAIc-IPnWX3FepDdtBnFVw9LgpPZc"></div>`
`<script type="text/javascript" src="https://www.google.com/recaptcha/api.js?hl=en"></script>`

Thanks!

**Comment by sepiariver** [comment]
Hmm... I'll have to look into this. Not sure if the underlying ReCaptcha library supports this...

**Comment by 5koder** [comment]
Thank you! Much appreciated

**Comment by sepiariver** [comment]
Hi @5koder I'm sorry all the solutions I've found to do multiple recaptchas on the page, involve cloning the element in the browser using jQuery. I don't love any of those solutions, so I wouldn't recommend it, but you can find them by googling "multiple recaptcha on same page" or something like that.

Thanks for using MODX and RecaptchaV2 :D

**Comment by 5koder** [comment]
Thanks for checking it out. Will do some googling

**Comment by 5koder** [comment]
@sepiariver Thanks for checking it out. Will do some googling

**Comment by MicrowaveDev** [comment]
@sepiariver http://stackoverflow.com/a/28126317/6053486 - good solution
