### ISSUE TITLE
How can i change it's THEME from default to "Dark"???

### ISSUE THREAD

**Issue by syberknight** [sepiariver/recaptchav2#9]
hiho.

i've installed the reCAPTCHAv2 extra (in my ModX Revolution v.2.4.2-pl), and _it works_!!!

but i cannot seem to figure out **how to change its THEME** from light **to DARK**.

it seems like it should be simple (outside of modx), but within this extra, i'm lost.

thanks.-jason.

**Comment by syberknight** [comment]
FYI, in case it'll help anyone else... i figured out a way to do this. can read the solution @ https://forums.modx.com/thread/99538/recaptcha-v2-how-to-change-it-039-s-theme#dis-post-538291

**Comment by sepiariver** [comment]
Thanks @syberknight for posting that :D It's nice that they built the theme setting into their data-attribute interface, it makes it very easy to configure. I'm going to add your solution to the readme, if you don't mind.

**Comment by syberknight** [comment]
hi @sepiariver - OF COURSE - share with the world. it was a total fluke that i stumbled across that. i only tried it because i'd tried everything else & was grasping for straws. my jaw dropped when it worked (LOL). thanks for the great plugin!
